name: Go CI/CD  

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - run: go mod tidy
      # - run: go test -v -timeout 2m -coverprofile=coverage.out ./...
      - uses: codecov/codecov-action@v3
      - name: Codecov  
        uses: codecov/codecov-action@v3  

  build:  
    needs: test  
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v4  
      - uses: actions/setup-go@v4  
      - run: go build -ldflags="-X 'main.Version=$(git describe --tags)'" -o csv2json ./cmd/converter  
      - uses: softprops/action-gh-release@v1  
        if: github.ref == 'refs/heads/main'  
        with:  
          files: csv2json  